### ISSUE TITLE
[Issue]: Notice with RCON Command send message without space and tries to put underline in each space

### ISSUE THREAD

**Issue by moonshadowrev** [ddakebono/PalworldRcon#13]
![image](https://github.com/user-attachments/assets/12fd405f-e6a9-4262-8700-99c518978afd)
```cs
public async void SendNotice(string notice)
    {
        if(string.IsNullOrWhiteSpace(notice) || Status != ClientStatus.Connected) return;

        notice = notice.Replace(" ", "_");

        await SendAsync($"Broadcast {notice}");
    }
```

**Comment by ddakebono** [comment]
This was done on purpose due to issues with how palworlds server rcon functions worked, I haven't been following changes since I started this project so I don't know if this has been fixed yet.

You can try sending the broadcast from the console and see if spaces work there, if they do then the replace is no longer needed.

Since I'm not actively playing palworlds right now and have quite a few other things taking up my time I don't know if I'll be able to look into things right away.
